project:
  type: book

book:
  title: "AWS Cloud Practitioner Notes"
  author: "Kalonji Tshisekedi"
  date: "7/10/2024"
  chapters:
    - index.qmd

    - part: module-1-notes/Introduction.qmd
      chapters:
        - module-1-notes/Cloud-Computing.qmd

    - part: module-2-notes/Module-2-Amazon-EC2.qmd
      chapters:
        - module-2-notes/Amazon-EC2-Instance-Types.qmd
        - module-2-notes/Amazon-EC2-pricing.qmd
        - module-2-notes/Scaling-Amazon-EC2.qmd
        - module-2-notes/Elastic-Load-Balancing.qmd
        - module-2-notes/Messaging-and-Queuing.qmd
        - module-2-notes/Additional-Compute-Services.qmd

    - part: module-3-notes/Introduction-module-3.qmd
      chapters:
        - module-3-notes/AWS-Global-Infrastructure.qmd
        - module-3-notes/Edge-Locations.qmd
        - module-3-notes/How-to-Provision-AWS .qmd

    - part: module-4-notes/1-Introduction-m4.qmd
      chapters:
        - module-4-notes/2-Connectivity-to-AWS.qmd
        - module-4-notes/3-Subnets-and-NACL.qmd
        - module-4-notes/4-Global-Networking.qmd

    - part: module-5-notes/1-Introduction-m5.qmd
      chapters:
        - module-5-notes/2-Amazon-EBS.qmd
        - module-5-notes/3-Amazon-S3.qmd
        - module-5-notes/4-Amazon-EFS.qmd
        - module-5-notes/5-Amazon-RDS.qmd
        - module-5-notes/6-Amazon-DynamoDB.qmd
        - module-5-notes/7-Amazon-Redshift.qmd
        - module-5-notes/8-AWS-DMS.qmd
        - module-5-notes/9-Additional_database_service.qmd

    - part: module-6-notes/1-Introduction.qmd
      chapters:
        - module-6-notes/1-Introduction.qmd
        - module-6-notes/2-AWS-sahred.qmd
        - module-6-notes/3-AWS-permission.qmd
        - module-6-notes/4-AWS-Organisations.qmd
        - module-6-notes/5-Compliance.qmd
        - module-6-notes/6-Denial-of-Service-Attacks.qmd
        - module-6-notes/7-Additional-Security.qmd

format:
  html:
    theme: cosmo



