project:
  type: book

book:
  title: "aws-cp-notes"
  author: "Norah Jones"
  date: "7/10/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

