project:
  type: book

book:
  title: "AWS Cloud Practitioner Notes"
  author: "Kalonji Tshisekedi"
  date: "7/10/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - cloud-computing.qmd
    - summary.qmd

format:
  html:
    theme: cosmo



